AQ messaging example update
helidon-io/helidon-examples pull request #100
Opened 2024-10-30 16:23 UTC by danielkec

2024-11-04 08:35 UTC, senivam requested changes

2024-11-04 08:35 UTC, senivam commented on examples/messaging/docker/oracle-aq/Dockerfile
> +ENV "ORACLE_PWD"="frank"
remove line 18 and if possible change the password to 'changeit'

2024-11-04 08:35 UTC, senivam commented on examples/messaging/oracle-aq-websocket-mp/src/main/resources/application.yaml
> +# Copyright (c) 2020, 2024 Oracle and/or its affiliates.
in new files it's enough to have one CP year

2024-12-04 08:44 UTC, danielkec commented on examples/messaging/docker/oracle-aq/Dockerfile
> +ENV "ORACLE_PWD"="frank"
It is used across messaging examples, such change should belong to standalone PR

2024-12-04 08:51 UTC, senivam approved these changes, later dismissed
LGTM

2024-12-04 16:26 UTC, senivam approved these changes
LGTM

2024-12-04 16:38 UTC, merged